[package]
name = "bevy_spine"
version = "0.11.0-dev"
edition = "2024"
description = "Spine plugin for Bevy utilizing rusty_spine"
homepage = "https://github.com/supdrewin/bevy_spine"
repository = "https://github.com/supdrewin/bevy_spine"
readme = "readme.md"
license-file = "LICENSE"
exclude = ["assets/*"]

[features]
default = ["default_2d_materials"]

rayon = []

normal_material = ["2d", "default_shader"]
additive_material = ["2d", "default_shader"]
multiply_material = ["2d", "default_shader"]
screen_material = ["2d", "default_shader"]
normal_pma_material = ["2d", "default_shader"]
additive_pma_material = ["2d", "default_shader"]
multiply_pma_material = ["2d", "default_shader"]
screen_pma_material = ["2d", "default_shader"]

default_shader = []

default_2d_materials = [
    "normal_material",
    "additive_material",
    "multiply_material",
    "screen_material",
    "normal_pma_material",
    "additive_pma_material",
    "multiply_pma_material",
    "screen_pma_material",
]

default_3d_material = ["3d"]

2d = ["bevy/bevy_sprite_render"]
3d = ["bevy/bevy_pbr"]

debug = []

[dependencies]
glam = { version = "0.30", features = ["mint"] }
thiserror = "2"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
default-features = false
features = ["bevy_asset", "bevy_render"]

[dependencies.rusty_spine]
git = "https://github.com/supdrewin/rusty_spine"
branch = "3.8"

[dev-dependencies]
lerp = "0.5"
bevy = { git = "https://github.com/bevyengine/bevy", default-features = true }

[workspace]
members = ["ci"]
